CREATE TABLE IF NOT EXISTS `epb` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NOT NULL UNIQUE,
    `category` VARCHAR(100) DEFAULT NULL,
    `hero_content` LONGTEXT NOT NULL,
    `features_content` LONGTEXT NOT NULL,
    `hero_image` VARCHAR(255) DEFAULT NULL,
    `published` BOOLEAN DEFAULT TRUE,
    `published_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

