name: PHP Syntax Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  syntax-check:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      
      - name: Check PHP syntax
        run: |
          echo "Проверка синтаксиса PHP файлов..."
          find . -type f -name "*.php" ! -path "./vendor/*" -exec php -l {} \;
      
      - name: Validate composer.json
        run: |
          if [ -f composer.json ]; then
            composer validate --no-check-publish
          fi

