name: Code Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-check:
    name: PHP & JavaScript Syntax Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      
      - name: Check PHP syntax
        run: |
          echo "Проверка синтаксиса PHP файлов..."
          find . -type f -name "*.php" ! -path "./vendor/*" -exec php -l {} \;
      
      - name: Validate composer.json
        run: |
          if [ -f composer.json ]; then
            composer validate --no-check-publish
          fi
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install npm dependencies
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --no-save
            fi
          fi
      
      - name: Run ESLint
        run: |
          if [ -f package.json ]; then
            echo "Проверка синтаксиса JavaScript файлов..."
            npm run lint
          else
            echo "package.json не найден, проверка JavaScript пропущена"
          fi

